### ISSUE TITLE
purposes

### ISSUE THREAD

**Issue by IgorKey** [luca992/kEasySocket#2]
Nice job!
What's the main reason for this library?
there is ws support in https://github.com/korlibs/korio
also we are waiting for JB guys [here](https://github.com/ktorio/ktor/issues/1215)

**Comment by luca992** [comment]
Hi, it's basically supposed to be a super simple no dependency native websocket library based on a this c++ [library](https://github.com/dhbaird/easywsclient). It pretty much only uses posix operating system apis. I also added support for [websocket over ssl using openssl](https://github.com/machinezone/IXWebSocket). But, I haven't really been using/actively maintaining this lately... there defintely room for improvement.  

Also, korio did not exist when I created this project.

**Comment by luca992** [comment]
It also has a basic client implementation of Phoenix Channels

**Comment by IgorKey** [comment]
Thx
